version: '2'

services:
  nginx:
    image: smebberson/alpine-nginx:3.0.0
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/:/var/log/nginx/
      - ./collect.sh:/collect.sh
    ports:
      - 80:80
  couchdb:
    image: klaemo/couchdb:1.6
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./data:/usr/local/var/lib/couchdb
